export const LOAD_COURSES_SUCCES = "LOAD_COURSES_SUCCES";
export const LOAD_AUTHORS_SUCCES = "LOAD_AUTHORS_SUCCES";
export const CREATE_COURSES_SUCCES = "CREATE_COURSES_SUCCES";
export const UPDATE_COURSES_SUCCES = "UPDATE_COURSES_SUCCES";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
